image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - hugo --baseURL="http://a1s0.gitlab.io/ChangeBlog"
  artifacts:
    paths:
    - public
  only:
  - main
