baseURL = "https://alansolidum.com"
languageCode = "en-us"
title = "CHANGEBLOG by Alan Solidum"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-5768774-6"

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Alan Solidum"
  description = "My online log for documenting personal projects"

  # Link custom assets relative to /static
  custom_css = [ "custom.css" ]
  custom_js  = []
  favicon    = "img/favicon.png"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

# Navigation Section
  [params.navigation]
    title = "CHANGEBLOG"
    subtitle = "By Alan Solidum"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "About"
      url = "about"

  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
     title = "Hi, I'm the banner"
     subtitle = "I'm the subtitle"
     buttonText = "Get Started"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "Securing the Changeblog Images"
      subtitle = "using git hooks"
      image = "securing_changeblog.gif"
      url = "posts/securing-changeblog-images"

    [[params.tiles.showcase]]
      title = "Making Ornaments"
      subtitle = "with the 3d printer"
      image = "snowflake_all.jpg"
      url = "posts/making-ornaments"

    [[params.tiles.showcase]]
      title = "Showcase 2"
      subtitle = "Sub 2"
      image = "pic02.jpg"
      url = "blogs/tempus"

    [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "Massa libero"
    subtitle = """Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero. 
    Mauris aliquet magna magna sed nunc rhoncus pharetra. 
    Pellentesque condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia pellentesque lorem ipsum dolor. 
    Nullam et orci eu lorem consequat tincidunt. Vivamus et sagittis libero.
    Mauris aliquet magna magna sed nunc rhoncus amet pharetra et feugiat tempus."""
    buttonText = "Get Started"
    url = "posts/hello-world"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"

    formEndpoint = "https://smartforms.dev/submit/60b143ef32d3172d393a45dd"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "hi@alansolidum.com"

    [[params.contact.phone]]
    title = "Phone"
    phone = "(000) 000-0000 x1234"

    [[params.contact.address]]
    title = "Address"
    street = "Street"
    city = "City, ST 00000"
    country = "Country"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Company Name"

    # Uses font awesome icons
    [[params.footer.social]]
      icon = "fa-facebook"
      url= "https://www.facebook.com/alan.solidum"
      label = "Facebook"

    [[params.footer.social]]
      icon = "fa-instagram"
      url= "https://www.instagram.com/surfingsoul"
      label = "Instagram"
    
    [[params.footer.social]]
      icon = "fa-twitter"
      url= "https://twitter.com/asolidum"
      label = "Twitter"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/in/alansolidum"
      label = "LinkedIn"
      
    [[params.footer.social]]
      icon = "fa-github"
      url= "https://github.com/asolidum"
      label = "GitHub"

    [[params.footer.social]]
      icon = "fa-gitlab"
      url= "https://gitlab.com/a1s0"
      label = "GitLab"

    [[params.footer.quicklinks]]
      text = "3D Printer: "
      url= "https://www.thingiverse.com/a1s0"
      alt = "Thingiverse"
