baseURL = "https://alansolidum.com"
languageCode = "en-us"
title = "CHANGEBLOG by Alan Solidum"
theme = "forty"

enableGitInfo = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-5768774-6"

# Enter your disqus shortname to enable comments
disqusShortname = ""

enableEmoji = true

[taxonomies]
# Use singular rather than plural for default taxonomies
tag = "tag"
category = "category"

# Following lines allow rendering of RAW HTML
# eg. <img> tags
[markup.goldmark.renderer]
unsafe= true

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Alan Solidum"
  description = "Alan Solidum designed a mobile SDK with complementary Ruby on Rails/Golang API backend that integrated into 100+ apps (parking, dating, travel, etc)"

  # Enter your code to enable Google tracking
  googleOptimize = "OPT-M9N3CHM"
  googleTagManager = "GTM-MGZHSC"

  # Link custom assets relative to /static
  custom_css = [ "custom.css" ]
  custom_js  = []
  favicon    = "img/favicon.png"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

# Navigation Section
  [params.navigation]
    title = "CHANGEBLOG"
    subtitle = "By Alan Solidum"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "About"
      url = "about"

    [[params.navigation.links]]
      name = "Projects"
      url = "category/projects"

    [[params.navigation.links]]
      name = "Photos"
      url = "category/photos"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
     title = "Hello World"
     subtitle = "As a software/data engineer with diverse industry experience (advertising, robotics, and more), I have a passion for gathering/analyzing data to optimize systems. I have developed data products that generated an average monthly recurring revenue of $53K and built a mobile SDK with a complementary RoR/Golang API backend that reached an install base of over 50 million iOS/Android devices."
     buttonText = "Read This For More"
     url = "about"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "Storage Case Base Template"
      subtitle = "A SCAD storage solution featured on Hackaday"
      image = "scbt.gif"
      url = "posts/storage-case-base-template"

    [[params.tiles.showcase]]
      title = "Daily Fla.sh (inspired by 1 Second Everyday)"
      subtitle = "scripted with Bash and FFMpeg"
      image = "iterm_bash_ffmpeg_dailyflash_view.webp"
      url = "posts/daily-flash"

    [[params.tiles.showcase]]
      title = "Validating Media Uploads"
      subtitle = "with the Google Photos Java API client"
      image = "google_photos.webp"
      url = "posts/validating-media-uploads"

    [[params.tiles.showcase]]
      title = "Securing Changeblog Images"
      subtitle = "using git hooks"
      image = "securing_changeblog.gif"
      url = "posts/securing-changeblog-images"

    [[params.tiles.showcase]]
      title = "DIY Solder Fume Extractor"
      subtitle = "built with a fan, filter and filament"
      image = "fan_cover.png"
      url = "posts/solder-fume-extractor"

    [[params.tiles.showcase]]
      title = "Making Ornaments"
      subtitle = "with the 3d printer"
      image = "snowflake_all.webp"
      url = "posts/making-ornaments"

    [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = false
    title = "Hello World"
    subtitle = "As a software/data engineer with broad experience in several industries (advertising, satellite comms, robotics and more), I enjoy gathering/analyzing data and optimizing systems. I developed data products that generated an average monthly recurring revenue of $53K. Recently, I've built a mobile SDK with a complementary RoR/Golang API backend that eventually grew to an install base of over 50+ million iOS/Android devices."
    buttonText = "Read This For More"
    url = "about"

  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Get In Touch"
    buttonClear = "Clear"

    formEndpoint = "https://smartforms.dev/submit/60b143ef32d3172d393a45dd"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "hi@alansolidum.com"

    [[params.contact.phone]]
    title = "Phone"
    phone = "(000) 000-0000 x1234"

    [[params.contact.address]]
    title = "Address"
    street = "Street"
    city = "City, ST 00000"
    country = "Country"

  # Footer section
  [params.footer]
    enable = true
    copyright = "2022 AlanSolidum.com"

    # Uses font awesome icons
    [[params.footer.social]]
      icon = "fa-facebook"
      url= "https://www.facebook.com/alan.solidum"
      label = "Facebook"

    [[params.footer.social]]
      icon = "fa-instagram"
      url= "https://www.instagram.com/surfingsoul"
      label = "Instagram"
    
    [[params.footer.social]]
      icon = "fa-youtube"
      url= "https://www.youtube.com/AlanSolidum"
      label = "YouTube"

    [[params.footer.social]]
      icon = "fa-twitter"
      url= "https://twitter.com/asolidum"
      label = "Twitter"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/in/alansolidum"
      label = "LinkedIn"

    [[params.footer.social]]
      icon = "fa-angellist"
      url= "https://angel.co/u/also"
      label = "AngelList"

    [[params.footer.social]]
      icon = "fa-coffee"
      url= "https://ko-fi.com/also_"
      label = "Ko-fi Donation"

    [[params.footer.social]]
      icon = "fa-github"
      url= "https://github.com/asolidum"
      label = "GitHub"

    [[params.footer.social]]
      icon = "fa-gitlab"
      url= "https://gitlab.com/a1s0"
      label = "GitLab"

    [[params.footer.quicklinks]]
      text = ""
      url= "https://www.thingiverse.com/a1s0"
      alt = "Thingiverse"

    [[params.footer.quicklinks]]
      text = ""
      url = "https://www.printables.com/social/281662-also/about"
      alt = "Printables"

    [[params.footer.quicklinks]]
      text = ""
      url = "https://www.instructables.com/member/a1s0"
      alt = "Instructables"
